#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* Tugas Besar IF2211 Strategi Algortima 2 */
/* Topik : DFS dan BFS */
/* Kelompok - Aegis */
/* Anggota :
 * Gisela Supardi -
 * Erick Wijaya   - 13515057
 * Audry Nyonata  -
 */

void FollowBlackLine();

task main()
{



}

void FollowBlackLine(){
  int threshold = 65;

  // sensor sees light:
  if(getColorReflected(colorSensor) < threshold)
  {
    // counter-steer right:
    motor[leftMotor]  = 15;
    motor[rightMotor] = 55;
  }
  // sensor sees dark:
  else
  {
    // counter-steer left:
    motor[leftMotor]  = 55;
    motor[rightMotor] = 15;
  }
}
